spring:
  application:
    name: demo-shiro
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3316/demoshiro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  devtools:
    restart:
      enabled: false
    
server:
  port: 8080
  servlet:
    context-path: /demoshiro
mybatis:
  type-aliases-package: com.sly.demo.*.model
